name: Continuous Integration and Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install awscli -y

      - name: Make build.sh executable
        run: chmod +x build.sh

      - name: Build
        run: ./build.sh

      - name: Run tests
        run: echo "Running tests..." # Add actual test commands here

      - name: Package
        run: tar -czvf application.tar.gz dist/

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{AKIA2UC3DZM3GF2OF423}}
          aws configure set aws_secret_access_key ${{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 }}
          aws configure set default.region eu-north-1

      - name: Upload and Deploy to AWS EC2
        env:
          SSH_KEY: ${{ ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCdeRK/FkSzaJ1BhQvVoDwUG5KoI97CSzjBEpOAPZET4QwOKEt0ofqtvngFdb2KZ4o4xAo3o0bb6s1xf4wALjLd31R1nLWLrIW4va5u9QrTaa30oPKo+mOGNkmD7+toxkJd/w5JeKa4oKM31MPDsOQndZWgj+wXJKrZxpus2eQxhCb7IWO1oL4zNr6YdLEFWfZbQeXyJ5wkViU7R3H3bfMkvnW7j+2tGU2LvVeNwYjJNzId0qWEwvmgPJWwIRJmZDcXf/YmSFXucHcGnCDcOmd9zJaXO69oIJUhuKy3AYvTbI2zMdi+etPXJqp8z7bTg5HIDXTixYwCnW+wlNhDN9u4ayF9t2foZBfGYB8ZlwHgiki5kDuvpgxwa7tXu+RfacZKW1UyArE9TyjIGPOmLizDLlX2TFGCZoWi1eVeU4uNBucCKhkxms0DM+Ii0eiigcMpt5mRVfVdaiTYlyk8kFf7/mY/guQVvnVLSuVUGRtxZ8wu+4eIwES3BqsDtYbHVIS/BUXQF5witZbAOmAgJnWQbz/fxIOs/XmK0Si428Cc0r7zVrnASlHi9jGwUpARJ25U8Lbf9ZsB268yA6st9w2AmyEEQD/cqUeW3IM/PMNF9RQFivMHhz2VKdYFr4ACreFZDWh3ZYnrtoB17tNF/StI4HQwFfpymRi78KxRer8LyQ== stacylozovan@gmail.com
 }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" | base64 --decode > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H your-instance.amazonaws.com >> ~/.ssh/known_hosts
          scp -i ~/.ssh/id_rsa application.tar.gz ec2-16-171-31-138.eu-north-1.compute.amazonaws.com:/var/www/html/
          ssh -i ~/.ssh/id_rsa ec2-16-171-31-138.eu-north-1.compute.amazonaws.com "tar -xzvf /var/www/html/application.tar.gz -C /var/www/html/"
