# .github/workflows/ci.yml
name: Continuous Integration and Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: ./build.sh

      - name: Run tests
        run: echo "Running tests..." # Replace this with actual test commands

      - name: Package
        run: tar -czvf application.tar.gz dist/
