name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 --decode > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan your-instance.public.dns.com >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        scp -i ~/.ssh/id_rsa -r ./ ec2-16-171-31-138.eu-north-1.compute.amazonaws.com:/main
        ssh -i ~/.ssh/id_rsa ec2-16-171-31-138.eu-north-1.compute.amazonaws.com 'bash -s' < deploy_script.sh
