name: Deploy and Restart Nginx

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install SSH
      run: sudo apt-get update && sudo apt-get install -y openssh-client

    - name: Deploy via SSH
      uses: easingthemes/ssh-deploy@v2.1.6
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY_AWS }}
        REMOTE_HOST: ${{ secrets.SERVER_IP }}
        REMOTE_USER: ubuntu
        REMOTE_PORT: 22
        SOURCE: "."
        TARGET: "/var/www/html"

    - name: Restart Nginx
      run: sudo systemctl restart nginx
      
