name: Deploy and Restart Nginx

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install SSH
      run: apt-get update && apt-get install -y openssh-client

    - name: Deploy via SSH
      uses: easingthemes/ssh-deploy@v2.1.6
      with:
        server: ${{ secrets.SERVER_IP }} 
        username: ubuntu 
        password: ${{ secrets.SSH_KEY_AWS }}  
        localPath: "." 
        remotePath: "/var/www/html"  

    - name: Restart Nginx
      run: sudo systemctl restart nginx
